/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.Animated;

class AnimatedTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testAnimatedCreation():Void {
    // arrange
    var frames = [1, 2, 3];
    var frameTime = [0.1, 0.1, 0.1];
    var frameInterpolations = [null, null, null];

    // act
    var animated = new Animated<Int>(frames, frameTime, frameInterpolations);

    // assert
    Assert.notNull(animated);
    Assert.equals(0.0, animated.time);
  }

  public function testAnimatedUpdate():Void {
    // arrange
    var frames = [1, 2, 3];
    var frameTime = [0.1, 0.1, 0.1];
    var frameInterpolations = [null, null, null];
    var animated = new Animated<Int>(frames, frameTime, frameInterpolations);

    // act
    animated.update(0.05);

    // assert
    Assert.equals(0.05, animated.time);
  }

  public function testAnimatedLoop():Void {
    // arrange
    var frames = [1, 2, 3];
    var frameTime = [0.1, 0.1, 0.1];
    var frameInterpolations = [null, null, null];
    var animated = new Animated<Int>(frames, frameTime, frameInterpolations,
      true);

    // act
    animated.update(0.4); // More than total time (0.3)

    // assert
    Assert.isTrue(animated.time < 0.3); // Should loop back
  }

  public function testAnimatedNoLoop():Void {
    // arrange
    var frames = [1, 2, 3];
    var frameTime = [0.1, 0.1, 0.1];
    var frameInterpolations = [null, null, null];
    var animated = new Animated<Int>(frames, frameTime, frameInterpolations,
      false);

    // act
    animated.update(0.4); // More than total time (0.3)

    // assert
    Assert.equals(0.3, animated.time); // Should clamp to total time
  }
}
