/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.FileStream;
import recharge.midlife.base.FileStream.FileMode;

import haxe.io.Bytes;

class FileStreamTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testFileStreamCreation():Void {
    // arrange & act
    var fileStream = new FileStream(FileMode.READ);

    // assert
    Assert.notNull(fileStream);
  }

  public function testFileStreamCreationWithMode():Void {
    // arrange & act
    var readStream = new FileStream(FileMode.READ);
    var writeStream = new FileStream(FileMode.WRITE);

    // assert
    Assert.notNull(readStream);
    Assert.notNull(writeStream);
  }

  public function testFileStreamOpenNonExistentFile():Void {
    // arrange
    var fileStream = new FileStream(FileMode.READ);

    // act
    var result = fileStream.open("non_existent_file.txt");

    // assert
    Assert.isFalse(result);
  }

  public function testFileStreamGetDataStringWithoutFile():Void {
    // arrange
    var fileStream = new FileStream(FileMode.READ);

    // act & assert
    Assert.raises(function() {
      fileStream.getDataString();
    }, String);
  }

  public function testFileStreamGetDataBytesWithoutFile():Void {
    // arrange
    var fileStream = new FileStream(FileMode.READ);

    // act & assert
    Assert.raises(function() {
      fileStream.getDataBytes();
    }, String);
  }
}
