/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.graphics.LightArray;

class LightArrayTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testLightArrayCreation():Void {
    // arrange & act
    var lightArray = new LightArray();

    // assert
    Assert.notNull(lightArray);
  }

  public function testLightArraySetLight():Void {
    // arrange
    var lightArray = new LightArray();
    var position = vec4(1.0, 2.0, 3.0, 1.0);
    var color = vec4(0.5, 0.8, 0.2, 1.0);

    // act
    var lightId = lightArray.setLight(position, color);

    // assert
    Assert.equals(0, lightId); // First light should have ID 0
  }

  public function testLightArraySetLightWithId():Void {
    // arrange
    var lightArray = new LightArray();
    var position1 = vec4(1.0, 2.0, 3.0, 1.0);
    var color1 = vec4(0.5, 0.8, 0.2, 1.0);
    var position2 = vec4(4.0, 5.0, 6.0, 1.0);
    var color2 = vec4(0.9, 0.1, 0.3, 1.0);

    // act
    lightArray.setLight(position1, color1); // ID 0
    lightArray.setLight(position2, color2, 0); // Override ID 0

    // assert
    // Should not throw and should successfully override the light
    Assert.isTrue(true);
  }

  public function testLightArrayMultipleLights():Void {
    // arrange
    var lightArray = new LightArray();
    var position1 = vec4(1.0, 2.0, 3.0, 1.0);
    var color1 = vec4(0.5, 0.8, 0.2, 1.0);
    var position2 = vec4(4.0, 5.0, 6.0, 1.0);
    var color2 = vec4(0.9, 0.1, 0.3, 1.0);

    // act
    var lightId1 = lightArray.setLight(position1, color1);
    var lightId2 = lightArray.setLight(position2, color2);

    // assert
    Assert.equals(0, lightId1);
    Assert.equals(1, lightId2);
  }
}
