/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.graphics.Mesh.Vertex;

class MeshTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testVertexCreation():Void {
    // arrange
    var pos = vec3(1.0, 2.0, 3.0);
    var uv = vec2(0.5, 0.5);
    var normal = vec3(0.0, 1.0, 0.0);

    // act
    var vertex = new Vertex(pos, uv, normal);

    // assert
    Assert.notNull(vertex);
    Assert.equals(pos, vertex.position);
    Assert.equals(uv, vertex.uv);
    Assert.equals(normal, vertex.normal);
  }

  public function testVertexCreationWithoutNormal():Void {
    // arrange
    var pos = vec3(1.0, 2.0, 3.0);
    var uv = vec2(0.5, 0.5);

    // act
    var vertex = new Vertex(pos, uv);

    // assert
    Assert.notNull(vertex);
    Assert.equals(pos, vertex.position);
    Assert.equals(uv, vertex.uv);
    Assert.notNull(vertex.normal);
  }
}
