/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.ui.UIButton;

class UIButtonTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testUIButtonCreation():Void {
    // arrange & act
    var button = new UIButton("TestButton");

    // assert
    Assert.notNull(button);
    Assert.equals("TestButton", button.name);
    Assert.notNull(button.textObject);
  }

  public function testUIButtonCreationWithParams():Void {
    // arrange
    var params = {
      text: "Click Me",
      dimensions: vec2(100, 30)
    };

    // act
    var button = new UIButton("TestButton", params);

    // assert
    Assert.notNull(button);
    Assert.equals("TestButton", button.name);
    Assert.notNull(button.textObject);
  }

  public function testUIButtonTextObject():Void {
    // arrange
    var params = {text: "Custom Text"};
    var button = new UIButton("TestButton", params);

    // act & assert
    Assert.notNull(button.textObject);
    // Can't test _text directly since it's private, but we can test textObject exists
  }

  public function testUIButtonDefaultText():Void {
    // arrange & act
    var button = new UIButton("TestButton");

    // assert
    Assert.notNull(button.textObject);
    // Can't test _text directly since it's private, but we can test textObject exists
  }
}
