/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.ui.UIElement;
import recharge.midlife.base.ui.UIElement.Anchor;

class UIElementTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testUIElementCreation():Void {
    // arrange & act
    var element = new UIElement("TestElement");

    // assert
    Assert.notNull(element);
    Assert.equals("TestElement", element.name);
    Assert.equals(vec2(8, 8), element.dimensions);
  }

  public function testUIElementCreationWithParams():Void {
    // arrange
    var params = {
      anchor: CENTER,
      dimensions: vec2(16, 16),
      offset: vec2(4, 4)
    };

    // act
    var element = new UIElement("TestElement", params);

    // assert
    Assert.notNull(element);
    Assert.equals("TestElement", element.name);
    Assert.equals(vec2(16, 16), element.dimensions);
  }

  public function testUIElementSetAnchor():Void {
    // arrange
    var element = new UIElement("TestElement");

    // act
    element.setAnchor(BOTTOM_RIGHT);

    // assert
    // Can't directly test _anchor since it's private, but we can test getPosition behavior
    var position = element.getPosition();
    Assert.notNull(position);
  }

  public function testUIElementDimensions():Void {
    // arrange
    var element = new UIElement("TestElement");
    var newDimensions = vec2(32, 24);

    // act
    element.dimensions = newDimensions;

    // assert
    Assert.equals(newDimensions, element.dimensions);
  }

  public function testUIElementSetOffset():Void {
    // arrange
    var element = new UIElement("TestElement");
    var offset = vec2(10, 10);

    // act
    element.setOffset(offset);

    // assert
    // Can't directly test _offset since it's private, but we can test getPosition behavior
    var position = element.getPosition();
    Assert.notNull(position);
  }

  public function testUIElementGetPositionTopLeft():Void {
    // arrange
    var element = new UIElement("TestElement");
    element.setAnchor(TOP_LEFT);

    // act
    var position = element.getPosition();

    // assert
    Assert.notNull(position);
  }
}
