/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.ui.UILabel;

class UILabelTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testUILabelCreation():Void {
    // arrange & act
    var label = new UILabel("TestLabel");

    // assert
    Assert.notNull(label);
    Assert.equals("TestLabel", label.name);
    // Can't test _text directly since it's private, but we can test creation succeeded
  }

  public function testUILabelCreationWithParams():Void {
    // arrange
    var params = {text: "Hello World"};

    // act
    var label = new UILabel("TestLabel", params);

    // assert
    Assert.notNull(label);
    Assert.equals("TestLabel", label.name);
    // Can't test _text directly since it's private, but we can test creation succeeded
  }

  public function testUILabelSetText():Void {
    // arrange
    var label = new UILabel("TestLabel");

    // act
    label.setText("New Text");

    // assert
    // Can't test _text directly since it's private, but we can test setText doesn't crash
    Assert.notNull(label);
  }

  public function testUILabelSetTextEmpty():Void {
    // arrange
    var label = new UILabel("TestLabel");

    // act
    label.setText("");

    // assert
    // Can't test _text directly since it's private, but we can test setText doesn't crash
    Assert.notNull(label);
  }

  public function testUILabelSetTextNullParams():Void {
    // arrange
    var params = null;

    // act
    var label = new UILabel("TestLabel", params);

    // assert
    // Can't test _text directly since it's private, but we can test creation succeeded
    Assert.notNull(label);
  }
}
