/*
 * AI GENERATED TEST FILE - This file was generated by an AI and may need human modification
 * to ensure proper testing coverage and correctness.
 */

package tests;

import utest.Assert;

import recharge.midlife.base.physics.World;

class WorldTest extends utest.Test {
  public function setupClass():Void {
    // optional: initialize test dependencies
  }

  public function teardownClass():Void {
    // optional: clean up test resources
  }

  public function testWorldCreation():Void {
    // arrange & act
    var world = new World("TestWorld");

    // assert
    Assert.notNull(world);
    Assert.equals("TestWorld", world.name);
    Assert.notNull(world.gravity);
    Assert.equals(0.0, world.gravity.x);
    Assert.equals(0.0, world.gravity.y);
    Assert.equals(0.0, world.gravity.z);
  }

  public function testWorldCreationWithGravity():Void {
    // arrange
    var gravity = vec3(0, -9.81, 0);
    var params = {gravity: gravity};

    // act
    var world = new World("TestWorld", params);

    // assert
    Assert.notNull(world);
    Assert.equals(gravity, world.gravity);
  }

  public function testWorldCreationWithParams():Void {
    // arrange
    var params = {testParam: "value"};

    // act
    var world = new World("TestWorld", params);

    // assert
    Assert.notNull(world);
    Assert.equals("TestWorld", world.name);
  }

  public function testWorldUpdate():Void {
    // arrange
    var world = new World("TestWorld");

    // act
    world.update(0.016); // 60 FPS frame time

    // assert
    Assert.notNull(world); // Basic test that update doesn't crash
  }
}
